### ISSUE TITLE
Consider addition RTTI to words

### ISSUE THREAD

**Issue by fomkin** [exploadcom/pravda#103]
## Overview

Now RTTI (runtime type information) becomes obvious. It's required by .NET transaction support, by debug purposes like stack and head printing and transaction introspection. Also it will remove necessarity of type-bounded arithmetic instructions. I see two approaches to implementation.

1. Use [BSON](http://bsonspec.org/) or [MessagePack](https://msgpack.org). Pros: it's are well-known standards, stable third-party implementations. Cons: this is _serialization_ formats, both don't support references, hard to mutate.
2. More domain-specific format. Pros: we can use advantages of our VM without compromises. Cons: need to write a lot of code, bugs are coming, NIH is a shame.

I'm inclined to the second approach.

## Proposal

This is specification pseudo-BNF of word format.

```
length := 0b00<6 bits of data>
       | 0b01<6 bits length>
       | 0b10<14 bits length>
       | 0b11<22 bits length>

bytes := length byte[&length]

int8    := 0x01
int16   := 0x02
int32   := 0x03
bigint  := 0x04
uint8   := 0x05
uint16  := 0x06
uint32  := 0x07
decimal := 0x08
boolean := 0x09
ref     := 0x0A
utf8    := 0x0B
array   := 0x0C
struct  := 0x0D

primitive_type := int8
               | int16
               | int32
               | bigint
               | uint8
               | uint16
               | uint256
               | double
               | boolean
               | ref

type := primitive_type
      | struct
      | array
      | utf8

int8_data    := bytes~1
int16_data   := bytes~2
int32_data   := bytes~4
bigint_data   := length bytes[&length]
uint8_data   := bytes~1
uint16_data  := bytes~2
uint32_data  := bytes~4
double_data := bytes~8 # strict IEEE-754 floating point number
ref_data     := bytes~4
boolean_data := bytes~1

primitive_data := int8 int8_data
                | int16 int16_data
                | int32 int32_data
                | bitint bigint_data
                | uint8 uint8_data
                | uint16 uint16_data
                | uint32 uint32_data
                | double double_data
                | ref ref_data
                | boolean

data := primitive_data
      | array primitive_type length data(primitive_type)[&length]
      | struct bytes length (bytes, primitive_data)[&length] # struct_name, [(field, field_value)]
      | utf8 bytes
```

`smth[num]` means that we duplicate `smth` structure `num` times. `byte[8]` means 8 bytes, 
`bytes~num` means that we _expect_ `num` of bytes (which length is dynamic).

`&length` refers to given `length` field and means an integer representation of that field. 

`(a, b)` means pair type, e.g. two values of `a` and `b` are written consecutively. 

`data(primitive_type)` means corresponding `*_data` structure for `primtive_type`

**Comment by pankratov** [comment]
> both don't support references

MessagePack supports extension types. So, you can define domain specific types.

**Comment by fomkin** [comment]
@pankratov MessagePack extension types looks good. But the more I watch, the less I like this format. Lack of format version is big concern. Also I think we trying to use tools (BSON/MP) looks like suitable but not actually suitable.

**Comment by vovapolu** [comment]
I don't think it would be hard to implement our own protocol. It seems quite simple, and it's an esential part of our vm.

**Comment by pankratov** [comment]
> struct length (utf8, primitive_data)[&length]
I think it should be data, not primitive_data

Do you consider binary data as an array of uint8 ?

**Comment by pankratov** [comment]
I think tuples (i.e. `tuple length (primitive_type data(primitive_type))[&length]`) are also might be useful.

**Comment by pankratov** [comment]
And here
> array primitive_type length data(primitive_type)[&length]

Why primitive? How can I define array of array, for example? Should I use refs ?

**Comment by pankratov** [comment]
Domain specific types (like _address_, _hash_ or _code_ , for example) could be separate types.

**Comment by sherzodv** [comment]
How about a name of a struct itself, I mean how are we going to separate different struct types being of the same structure?

**Comment by sherzodv** [comment]
Another concern here is an array of a variable length data, e.g. `array utf8 ...`. We won't be able neither to give its length nor have constant time indexed access to values.

**Comment by sherzodv** [comment]
> @sherzodv are we going to distinguish them? I thought it's something like a dictionary or map.

External mapping is OK too if we can guarantee that our data never moves. In other case things like dynamic cast would be in trouble :)

**Comment by fomkin** [comment]
1. Changed `decimal` to `double` (strict IEEE-754 floating point number)
2. Changed `int64` and `uint64` to `int256` and `uint256`

**Comment by vovapolu** [comment]
We need to somehow encode type signature of a word. It's needed in meta method signature and definitely will be needed in future meta information. So I suggest to introduce new `sign` structure:

**Comment by fomkin** [comment]
@vovapolu looks good.
